# Generated by Django 4.2.5 on 2024-02-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name ="person",
            options = {
                "verbose_name": "visible_person",
                "verbose_name_plural": "persons",
            },
        ),
        migrations.AddField(
            model_name ="filmwork",
            name ="file_path",
            field =models.FileField(
                blank =True, null = True, upload_to = "movies/", verbose_name = "file"
            ),
        ),
    ]
