# Generated by Django 4.2.5 on 2024-02-20 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_person_options_filmwork_file_path"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="genre",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="genrefilmwork",
            unique_together={("film_work", "genre")},
        ),
        migrations.AlterUniqueTogether(
            name="personfilmwork",
            unique_together={("film_work", "person", "role")},
        ),
    ]
