"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from split_settings.tools import include


load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
include(
    "components/checklist.py",
)


# Application definition
include(
    "components/app_def.py",
)


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
include(
    "components/database.py",
)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
include(
    "components/password.py",
)


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

include(
    "components/translations.py",
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
include(
    "components/static-files.py",
)


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
include(
    "components/auto_field.py",
)
